config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "index", to: "pages#index"
  get "recherche", to: "pages#recherche"
  get "a_propos", to: "pages#apropos"
  resources :categories, param: :id do
    get ':name', action: :show, on: :member
  end
  resources :recipes, param: :id do
    get ':name', action: :show, on: :member
  end
   get '/random', to: 'recipes#random'

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
  has_one_attached :photo
  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category
  has_one_attached :photo
  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/apropos_controller.rb
class AproposController < ApplicationController
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order(:name)
  end

  def show
    id, _ = params[:id].split('-')
    @category = Category.find(id)
    @recipes = @category.recipes.order(:name) if @category
    if @category.present?
      @breadcrumbs = [{ title: 'Home', url: root_path }, { title: 'Catégorie', url: categories_path }, { title: @category.name, url: category_path(@category) }]
    else
      @breadcrumbs = [{ title: 'Home', url: root_path }]
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if params[:section] == 'liste'
      @recipes = Recipe.all.order("name ASC")
    else
      @recipes_by_letter = Recipe.all.group_by { |recipe| recipe.name[0].upcase }
      .sort_by { |letter, _recipes| letter }
      @recipes = Recipe.all.order("name ASC")
    end

  end


  def recherche
    # Vérifiez si le paramètre de requête `query` est présent dans l'URL
    if params[:query].blank? || params[:controller] == 'recipes' && params[:action] == 'search'
      @recipes = Recipe.order("RANDOM()")
    else
      @recipes = Recipe.where("name ILIKE ? OR recipe ILIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    id, _ = params[:id].split('-')
    @recipe = Recipe.find(id)
    category_id = @recipe.category_id
    @next_recipe = Recipe.where("id > ? AND category_id = ?", @recipe.id, category_id).order(:id).first
    @previous_recipe = Recipe.where("id < ? AND category_id = ?", @recipe.id, category_id).order(id: :desc).first
     @category = @recipe.category
    if @category.present?
      @breadcrumbs = [{ title: 'Home', url: root_path }, { title: 'Catégorie', url: categories_path }, { title: @category.name, url: category_path(@category) }, { title: @recipe.name, url: recipe_path(@recipe) }]
    else
      @breadcrumbs = [{ title: 'Home', url: root_path }, { title: @recipe.name, url: recipe_path(@recipe) }]
    end
  end

  def random
    @recipe = Recipe.order("RANDOM()").first
    redirect_to recipe_path(@recipe)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 col-sm-6 title-category-list">Trouvez votre recette par catégorie</div>
    <% @categories.each do |cat| %>
      <div class="col-md-3 col-sm-6 mb-5">
        <%= link_to category_path(cat) do %>
          <div class="pic-card-category">
            <% if cat.photo.present? %>
<%= cl_image_tag(cat.photo.present? ? cat.photo.key : "landmannalaugar_iceland.jpg",
                 :transformation => [
                    {:width => 1000, :crop => "scale"},
                    {:quality => "auto"},
                    {:fetch_format => :auto}
                 ],
                 class: "card-img-top") %>            <% else %>
              <img src="https://library.elementor.com/food-blog-flexbox/wp-content/uploads/sites/232/2022/02/how2_Post_ft_image3.jpg" class="card-img-top" alt="...">
            <% end %>
          </div>
        <% end %>
          <div class="title-card-category">
            <%= cat.name %>
          </div>
          <div class="description-card-category">
            <%= cat.description %>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="row align-items-center p-40">
  <div class="col-lg-6  title-category-show"><%= @category.name %></div>
  <div class="col-lg-6 description-title-category"><%= @category.description %></div>
</div>

</div>

<%# listing %>
<%= render "shared/card-category" %>
<%= render 'shared/breadcrumb' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Charle's CookBook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/apropos.html.erb
<div class="container mt-5 h100vh">
  <div class="row">
    <div class="col-md-3 title-category-list mb-5">À Propos</div>
    <div class="col-lg-8 description-title-category">
    Passionné de cuisine depuis des années, vous retrouverez sur ce site, une grande partie des recettes que j'ai accumulées au fil des années.
    <br>
Durant plus de 1
  </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="pic-home-100" style="background-image:
  url(
    https://images.pexels.com/photos/6287251/pexels-photo-6287251.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2
  )">
</div>
<div class="row align-items-center">
  <div class="col-lg-6  title-category-show">CookBook •</div>
  <div class="col-lg-6 description-title-category">
    Passionné de cuisine depuis des années, retrouvez ici mon petit pense bête des recettes accumulées au fil du temps.
  </div>
</div>

app/views/pages/index.html.erb
 <div class="container mt-5 h100vh">
  <div class="row">
    <div class="col-md-3 title-category-list mb-5 justify-content-start">L'index des recettes
        <p style="font-size:20px">
        <%= link_to "nom", index_path(section: 'abc') %> |
        <%= link_to "Liste", index_path(section: 'liste') %>
      </p>
    </div>
     <div class="col-md-1"></div>

    <% if params[:section] == 'liste' || params[:section].nil? %>
     <% @recipes.each do |recipe| %>
          <div class="col-lg-2 col-md-3 col-sm-4 mb-4 title-category-list mt-3">
            <%= link_to recipe_path(recipe) do %>
            <div class="photo-category-recipe">
            <% if recipe.photo.present? %>
      <%= cl_image_tag(recipe.photo.present? ? recipe.photo.key : "landmannalaugar_iceland.jpg",
                      :transformation => [
                          {:width => 1000, :crop => "scale"},
                          {:quality => "auto"},
                          {:fetch_format => :auto}
                      ],
                      class: "card-img-top") %>      <% end %>
            </div>
            <% end %>
            <div class="details-category-recipe p-1">
              <div class="title-category-recipe-index">
                <% if recipe.photo.present? %>
                  <%= recipe.name %>
                <% else %>
                  <%= link_to recipe.name, recipe_path(recipe) %>
                <% end %>
                </div>
             </div>
          </div>
        <% end %>

    <% else %>
      <% @recipes_by_letter.each do |letter, recipes| %>
        <div class="col-md-3">
          <h1><%= letter %></h1>
          <ul class="list-unstyled">
            <% recipes.each do |recipe| %>
              <div class="link-read-more"><%= link_to recipe.name, recipe_path(recipe) %></div>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/recherche.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 col-sm-6 title-category-list">
      <span>Votre recherche</span>
      <span class="result-search"><%= params[:query] %></span>
    </div>
    <% @recipes.each do |recipe| %>
      <div class="col-md-3 col-sm-6 mb-5">
        <%= link_to recipe_path(recipe) do %>
          <div class="pic-card-category">
            <% if recipe.photo.present? %>
              <%= cl_image_tag recipe.photo.key, class: "card-img-top" %>
            <% else %>
              <img src="https://library.elementor.com/food-blog-flexbox/wp-content/uploads/sites/232/2022/02/how2_Post_ft_image3.jpg" class="card-img-top" alt="...">
            <% end %>
          </div>
        <% end %>
          <div class="title-card-category">
            <%= recipe.name %>
          </div>
          <div class="description-card-category">
            <%= recipe.description %>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-7 col-sm-12 bg-white d-flex flex-column justify-content-center">
      <p class="title-show-recipe"><%= @recipe.name %></p>
      <p class="resume-short-show-recipe"><%= @recipe.description %></p>
      <p class="resume-short-show-recipe">

</p>
    </div>
   <div class="col-lg-5 col-sm-12 p-0">
  <div class="photo-show-recipe">
    <% if @recipe.photo.present? %>
      <%= cl_image_tag(@recipe.photo.key, :transformation => [
        {:width => 1000, :crop => "scale"},
          {:quality => "auto"},
          {:fetch_format => :auto}
        ]) %>
    <% end %>
  </div>
</div>
      <div class="recipe-show-recipe px-2 py-4">
        <%= @recipe.recipe.html_safe %>
      </div>
  </div>
</div>
<%= render 'shared/breadcrumb' %>

app/views/shared/_breadcrumb.html.erb
<% if @breadcrumbs.any? %>
  <nav aria-label="breadcrumb">
     <ol class="breadcrumb">
      <% @breadcrumbs.each_with_index do |crumb, index| %>
        <% if index == @breadcrumbs.size - 1 %>
          <li class="breadcrumb-item active" aria-current="page"><%= crumb[:title] %></li>
        <% else %>
          <li class="breadcrumb-item"><a href="<%= crumb[:url] %>"><%= crumb[:title] %></a></li>
        <% end %>
      <% end %>
    </ol>

   </nav>
<% end %>
<%# previous & next %>
<!--
<% if @previous_recipe || @next_recipe %>
  <div class="next-prev-container">
    <div class="col-6 d-flex justify-content-start align-items-center ps-5">
      <% if @previous_recipe %>
        <%= link_to "<< Recette précédente", recipe_path(@previous_recipe), class: "link-read-more" %>
      <% end %>
    </div>
    <div class="col-6 d-flex justify-content-end align-items-center pe-5">
      <% if @next_recipe %>
        <%= link_to "Recette suivante >>", recipe_path(@next_recipe), class: "link-read-more" %>
      <% end %>
    </div>
  </div>
<% end %>
-->

app/views/shared/_card-category.html.erb
<div class="row mt-3 align-items-start">
  <% @recipes.each do |recipe| %>
    <div class="col-lg-4 col-md-6 col-sm-12 mb-4 title-category-list mt-3">
      <%= link_to recipe_path(recipe) do %>
      <div class="photo-category-recipe">
      <% if recipe.photo.present? %>
<%= cl_image_tag(recipe.photo.present? ? recipe.photo.key : "landmannalaugar_iceland.jpg",
                 :transformation => [
                    {:width => 1000, :crop => "scale"},
                    {:quality => "auto"},
                    {:fetch_format => :auto}
                 ],
                 class: "card-img-top") %>      <% end %>
      </div>
      <% end %>
      <div class="details-category-recipe p-4">
        <div class="title-category-recipe"><%= recipe.name %></div>
        <div class="description-card-category"><%= recipe.description %></div>
        <div class="link-read-more"><%= link_to 'voir la recette', recipe_path(recipe) %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer-container">
  <div class="d-flex footer-link">
    <%# link_to "A propos", a_propos_path, class: 'footer-link' %>
  </div>
  <div class="d-flex footer-link">
    © <%= Time.now.year %> conception <%= link_to "Charles Woehl", 'https://www.charleswoehl.fr', class: 'footer-link', target: '_blank' %>  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid iphone-padding">
    <%= link_to "Charle's CookBook •", root_path, class:'navbar-brand logo' %>

<div class="d-flex align-items-center">
    <a class="nav-link search-none" href="#" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fa-solid fa-magnifying-glass"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    </div>
    <!-- Liens pour les grands écrans -->
    <ul class="navbar-nav d-none d-lg-flex">
      <li class="nav-item">
        <%= link_to "Catégories", categories_path, class: ('nav-link' + (current_page?(categories_path) ? ' active' : '')) %>
      </li>
      <li class="nav-item">
        <%= link_to "Index", index_path(section: 'abc'), class: ('nav-link' + (current_page?(index_path) ? ' active' : '')) %>
      </li>
      <li class="nav-item">
        <%= link_to "Inspire moi !", '/random', class: ('nav-link') %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fa-solid fa-magnifying-glass"></i></a>
      </li>
    </ul>
  </div>
</nav>

<!-- Modal de recherche -->
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="searchModalLabel" aria-hidden="true">
  <div class="modal-dialog  modal-xl">
    <div class="modal-content rounded-4 px-4 py-2">
      <div class="modal-header">
        <h5 class="modal-title title-category-list text-center" id="searchModalLabel">Recherche</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="row justify-content-center">
  <div class="col-sm-12 my-3">
    <%= form_with url: recherche_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control rounded-start-4 py-2 ps-3",
            placeholder: "Mot clé, ingrédient, ..."
        %>
      <%= submit_tag "Recherche", name: "", class: "btn btn-primary rounded-end-4" %>
    <% end %>
  </div>
</div>
      </div>
    </div>
  </div>
</div>

<!-- Liens pour les petits écrans -->
<div class="container-fluid">
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav d-lg-none">
      <li class="nav-item">
        <%= link_to "Catégories", categories_path, class: ('nav-link' + (current_page?(categories_path) ? ' active' : '')) %>
      </li>
      <li class="nav-item">
        <%= link_to "Index", index_path, class: ('nav-link' + (current_page?(index_path) ? ' active' : '')) %>
      </li>
      <li class="nav-item pb-2">
        <%= link_to "Inspire moi !", '/random', class: ('nav-link') %>
      </li>
      <%# <li class="nav-item">
        <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fa-solid fa-magnifying-glass"></i></a>
      </li> %>
    </ul>
  </div>
</div>